import { Metadata } from 'next';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export const metadata: Metadata = {
//   title: "Your Page Title",
//   description: "A short description of your page content",
//   openGraph: {
//     title: "Your Page Title",
//     description: "A short description of your page content",
//     images: [
//       {
//         url: "https://www.digitalocean.com/cdn-cgi/image/quality=75,width=828/https://www.digitalocean.com/api/static-content/v1/images?src=https%3A%2F%2Fcommunity-cdn-digitalocean-com.global.ssl.fastly.net%2FQbUQdoFPxWTLdrrX9PkyMW4E&raw=1",
//         width: 1200,
//         height: 630,
//         alt: "A description of the image",
//       },
//     ],
//     type: "website",
//     locale: "en_US",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Your Page Title",
//     description: "A short description of your page content",
//     images: ["https://assets.digitalocean.com/articles/social-metadata/html-social-share.png"],
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
