import { Metadata } from 'next';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata: Metadata = {
  title: "Your Page Title",
  description: "A short description of your page content",
  openGraph: {
    title: "Your Page Title",
    description: "A short description of your page content",
    images: [
      {
        url: "https://example.com/path-to-your-image.jpg",
        width: 1200,
        height: 630,
        alt: "A description of the image",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Your Page Title",
    description: "A short description of your page content",
    images: ["https://example.com/path-to-your-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
