import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export const metadata: Metadata = {
//   title: "Your Page Title",
//   description: "A short description of your page content",
//   openGraph: {
//     title: "Your Page Title",
//     description: "A short description of your page content",
//     images: [
//       {
//         url: "https://www.digitalocean.com/cdn-cgi/image/quality=75,width=828/https://www.digitalocean.com/api/static-content/v1/images?src=https%3A%2F%2Fcommunity-cdn-digitalocean-com.global.ssl.fastly.net%2FQbUQdoFPxWTLdrrX9PkyMW4E&raw=1",
//         width: 1200,
//         height: 630,
//         alt: "A description of the image",
//       },
//     ],
//     type: "website",
//     locale: "en_US",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Your Page Title",
//     description: "A short description of your page content",
//     images: ["https://assets.digitalocean.com/articles/social-metadata/html-social-share.png"],
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          property="og:url"
          content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html"
        />
        <meta property="og:type" content="article" />
        <meta
          property="og:title"
          content="When Great Minds Don’t Think Alike"
        />
        <meta
          property="og:description"
          content="How much does culture influence creative thinking?"
        />
        <meta
          property="og:image"
          content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg"
        />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
